[package]
name = "typedown-incremental"
version.workspace = true
edition = "2024"
license = "AGPL-3.0-only"
description = "Incremental computation engine for Typedown"
repository = "https://github.com/Huy-DNA/typerighter"

[dependencies]
typedown-macros = { version = "0.11.1", path = "../typedown-macros" }
typedown-types = { version = "0.11.1", path = "../typedown-types" }
dashmap = "6.2.1"
inventory = "0.3.24"
rustc-stable-hash = "0.1"
memmap2 = "0.9"
tempfile = "3"
fs2 = { version = "0.4", optional = true }
rand = { version = "0.9", optional = true }

[features]
session = ["fs2", "rand"]
