import type {
  Component,
} from 'vue';
import {
  Archive,
  Apple,
  ArrowUpRight,
  AtSign,
  Atom,
  Bell,
  Binary,
  Bookmark,
  Box,
  Briefcase,
  Bug,
  Camera,
  Car,
  Calendar,
  ChartBar,
  ChartPie,
  Circle,
  CircuitBoard,
  CircleCheck,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Contact,
  Crown,
  Cpu,
  Database,
  Diamond,
  Droplet,
  Eye,
  Film,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Folder,
  Gamepad2,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Hash,
  Hammer,
  Hand,
  Headphones,
  Heart,
  Hexagon,
  Hourglass,
  House,
  Image,
  Inbox,
  Infinity,
  Info,
  Kanban,
  Key,
  Layers,
  Leaf,
  Library,
  Lightbulb,
  Link,
  Lock,
  Magnet,
  Mail,
  Map,
  Megaphone,
  MessageCircle,
  Mic,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Notebook,
  Paintbrush,
  Palette,
  Pen,
  Pencil,
  Phone,
  Pin,
  Pizza,
  Plane,
  Puzzle,
  Package,
  Radio,
  Rocket,
  School,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  Ship,
  Signpost,
  Snowflake,
  Square,
  Star,
  StickyNote,
  Sun,
  Sparkles,
  Table,
  Tag,
  Target,
  Terminal,
  ThumbsUp,
  Ticket,
  Timer,
  Trash2,
  TreePine,
  TrendingUp,
  Triangle,
  TriangleAlert,
  Trophy,
  User,
  Users,
  WandSparkles,
  Waves,
  Wrench,
  Zap,
  File,
  FileText,
  FileCode,
  BookOpen,
  BookMarked,
  Clipboard,
  Scroll,
} from '@lucide/vue';

const PAGE_ICONS: Record<string, Component> = {
  // Documents
  'file-text': FileText,
  file: File,
  notebook: Notebook,
  newspaper: Newspaper,
  scroll: Scroll,
  'book-open': BookOpen,
  'book-marked': BookMarked,
  clipboard: Clipboard,
  'sticky-note': StickyNote,
  'file-code': FileCode,
  // Folders & Organization
  folder: Folder,
  archive: Archive,
  box: Box,
  package: Package,
  briefcase: Briefcase,
  inbox: Inbox,
  layers: Layers,
  library: Library,
  // Communication
  mail: Mail,
  'message-circle': MessageCircle,
  megaphone: Megaphone,
  bell: Bell,
  phone: Phone,
  radio: Radio,
  send: Send,
  // People
  user: User,
  users: Users,
  contact: Contact,
  hand: Hand,
  // Nature
  leaf: Leaf,
  'flower-2': Flower2,
  'tree-pine': TreePine,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  mountain: Mountain,
  waves: Waves,
  snowflake: Snowflake,
  flame: Flame,
  droplet: Droplet,
  // Science & Tech
  'flask-conical': FlaskConical,
  atom: Atom,
  cpu: Cpu,
  code: Code,
  terminal: Terminal,
  database: Database,
  server: Server,
  bug: Bug,
  'circuit-board': CircuitBoard,
  binary: Binary,
  // Creative
  palette: Palette,
  pen: Pen,
  paintbrush: Paintbrush,
  camera: Camera,
  music: Music,
  film: Film,
  image: Image,
  mic: Mic,
  headphones: Headphones,
  // Status & Emotion
  heart: Heart,
  star: Star,
  flag: Flag,
  trophy: Trophy,
  target: Target,
  bookmark: Bookmark,
  'thumbs-up': ThumbsUp,
  'circle-check': CircleCheck,
  'triangle-alert': TriangleAlert,
  info: Info,
  sparkles: Sparkles,
  crown: Crown,
  // Abstract & Shapes
  circle: Circle,
  square: Square,
  diamond: Diamond,
  hexagon: Hexagon,
  triangle: Triangle,
  zap: Zap,
  hash: Hash,
  'at-sign': AtSign,
  infinity: Infinity,
  // Navigation & Travel
  compass: Compass,
  map: Map,
  globe: Globe,
  house: House,
  rocket: Rocket,
  plane: Plane,
  car: Car,
  ship: Ship,
  signpost: Signpost,
  // Time & Calendar
  clock: Clock,
  calendar: Calendar,
  timer: Timer,
  hourglass: Hourglass,
  // Tools & Objects
  wrench: Wrench,
  hammer: Hammer,
  key: Key,
  lock: Lock,
  shield: Shield,
  link: Link,
  magnet: Magnet,
  scissors: Scissors,
  lightbulb: Lightbulb,
  glasses: Glasses,
  // Data & Charts
  'chart-bar': ChartBar,
  'chart-pie': ChartPie,
  'trending-up': TrendingUp,
  table: Table,
  kanban: Kanban,
  // Education
  'graduation-cap': GraduationCap,
  school: School,
  pencil: Pencil,
  // Food & Drink
  coffee: Coffee,
  pizza: Pizza,
  apple: Apple,
  // Misc
  gift: Gift,
  puzzle: Puzzle,
  'gamepad-2': Gamepad2,
  ticket: Ticket,
  tag: Tag,
  pin: Pin,
  'trash-2': Trash2,
  'wand-sparkles': WandSparkles,
  eye: Eye,
  search: Search,
  settings: Settings,
  'arrow-up-right': ArrowUpRight,
};

export function getPageIcon (lucideName: string): Component | undefined {
  return PAGE_ICONS[lucideName];
}
