id = "typedown"
name = "Typerighter"
version = "${VERSION}"
schema_version = 1
authors = ["Lucas Nguyen"]
description = "Typedown - a structured type-safe markdown language"
repository = "https://github.com/huydo862003/typerighter"
languages = ["languages/typedown", "languages/typedown_yaml", "languages/typedown_md", "languages/typedown_md_inline"]

[language_servers.typedown-lsp]
name = "Typedown LSP"
languages = ["Typedown"]

[grammars.typedown]
repository = "${REPO_URL}"
rev = "${COMMIT_SHA}"
path = "packages/tree-sitter"

[grammars.typedown_yaml]
repository = "${REPO_URL}"
rev = "${COMMIT_SHA}"
path = "packages/tree-sitter/typedown-yaml"

[grammars.typedown_md]
repository = "${REPO_URL}"
rev = "${COMMIT_SHA}"
path = "packages/tree-sitter/typedown-md"

[grammars.typedown_md_inline]
repository = "${REPO_URL}"
rev = "${COMMIT_SHA}"
path = "packages/tree-sitter/typedown-md-inline"
