---
_label: "Graph Database"
_icon: icon.document
---

## Resources

- "Graph Databases" by Ian Robinson, Jim Webber, and Emil Eifrém
- [Neo4j Graph Database Documentation](https://neo4j.com/docs/)
- [Apache TinkerPop (Gremlin)](https://tinkerpop.apache.org/docs/current/)
- [W3C RDF Primer](https://www.w3.org/TR/rdf11-primer/)
- [ISO GQL Standard](https://www.iso.org/standard/76120.html)
- [ArangoDB Docs](https://www.arangodb.com/docs/)
- _Graph Databases_ - Ian Robinson, Jim Webber, Emil Eifrem (O'Reilly)

## Expected Topics to Research

- Philosophy of Graph Databases.
- The data model of Graph Databases.
- Query language of Graph Databases.
- Processing phases of Graph Databases.
- Implementation technique of Graph Databases.
