---
_label: "Introduction"
_icon: icon.document
---

This document details the motivation, design of Typedown & the research process into YAML 1.2 & graph database + web 3, to unify and incorporate them into note management. In the end, notes are interlinked documents, which resembles a graph or a web of documents. Incorporating semantic into this web will unlock various analysis & language services (LSP) for note management. Even, static site generators can be enabled based on the written notes.
