[package]
name = "typedown-server"
version.workspace = true
edition = "2024"
license = "AGPL-3.0-only"
description = "Typedown LSP and RPC server"
repository = "https://github.com/Huy-DNA/typerighter"
authors = ["Huy-DNA <huydo862003@gmail.com>"]

[[bin]]
name = "typedown-lsp"
path = "src/bin/typedown-lsp.rs"

[[bin]]
name = "typedown-rpc"
path = "src/bin/typedown-rpc.rs"

[lib]
crate-type = ["rlib"]

[features]
default = ["session"]
session = ["typedown-incremental/session"]

[dependencies]
anyhow = "1"
log = "0.4"
serde_json = "1"
serde = "1"
notify = "8.2.0"
crossbeam-channel = "0.5"
typedown-incremental = { version = "0.28.1", path = "../typedown-incremental" }
typedown-lang = { version = "0.28.1", path = "../typedown-lang", features = ["export"] }
typedown-types = { version = "0.28.1", path = "../typedown-types" }
lsp-types = "0.97"
lsp-server = "0.7"
ropey = "1.6.1"
dashmap = "6.2.1"
threadpool = "1"
ctrlc = "3"

[dev-dependencies]
tempfile = "3"
serde = "1"
filetime = "0.2"
