[package]
name = "typedown-types"
version.workspace = true
edition = "2024"
license = "AGPL-3.0-only"
description = "Core types for the Typedown language toolkit"
repository = "https://github.com/Huy-DNA/typerighter"
authors = ["Huy-DNA <huydo862003@gmail.com>"]

[dependencies]
unescaper = "0.2"
html-escape = "0.2"
num_enum = "0.7"
