import type {
  Component,
} from 'vue';
import {
  Archive,
  Apple,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  AtSign,
  Atom,
  Bell,
  Binary,
  Bluetooth,
  Bookmark,
  BookMarked,
  BookOpen,
  Box,
  Briefcase,
  Bug,
  Calendar,
  Camera,
  Car,
  ChartBar,
  ChartPie,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleHelp,
  CircuitBoard,
  Clipboard,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Contact,
  Copy,
  Crosshair,
  Crown,
  Cpu,
  Database,
  Diamond,
  Download,
  Droplet,
  ExternalLink,
  Eye,
  File,
  FileCode,
  FileText,
  Film,
  Filter,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Folder,
  Gamepad2,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Hammer,
  Hand,
  Hash,
  Headphones,
  Heart,
  Hexagon,
  Hourglass,
  House,
  Image,
  Inbox,
  Infinity,
  Info,
  Kanban,
  Key,
  Layers,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  Link,
  List,
  Loader,
  Lock,
  LogIn,
  LogOut,
  Magnet,
  Mail,
  Map,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  Mic,
  Minimize2,
  Minus,
  Moon,
  MoreHorizontal,
  Mountain,
  Move,
  Music,
  Newspaper,
  Notebook,
  Paintbrush,
  Palette,
  PanelLeft,
  Pause,
  Pen,
  Pencil,
  PencilLine,
  Phone,
  Pin,
  Pizza,
  Plane,
  Play,
  Plus,
  Power,
  Printer,
  Puzzle,
  Package,
  Radio,
  Redo2,
  RefreshCw,
  Rocket,
  RotateCw,
  Save,
  School,
  Scissors,
  Scroll,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  Ship,
  Skull,
  Sword,
  Swords,
  Signpost,
  Snowflake,
  Sparkles,
  Square,
  Star,
  StickyNote,
  Sun,
  Table,
  Tag,
  Target,
  Terminal,
  ThumbsUp,
  Ticket,
  Timer,
  Trash2,
  TreePine,
  TrendingUp,
  Triangle,
  TriangleAlert,
  Trophy,
  Undo2,
  Upload,
  User,
  Users,
  Volume2,
  WandSparkles,
  Waves,
  Wifi,
  Wrench,
  X,
  XCircle,
  Zap,
} from '@lucide/vue';

const PAGE_ICONS: Record<string, Component> = {
  // Documents
  'file-text': FileText,
  file: File,
  notebook: Notebook,
  newspaper: Newspaper,
  scroll: Scroll,
  'book-open': BookOpen,
  'book-marked': BookMarked,
  clipboard: Clipboard,
  'sticky-note': StickyNote,
  'file-code': FileCode,
  // Folders & Organization
  folder: Folder,
  archive: Archive,
  box: Box,
  package: Package,
  briefcase: Briefcase,
  inbox: Inbox,
  layers: Layers,
  library: Library,
  // Communication
  mail: Mail,
  'message-circle': MessageCircle,
  megaphone: Megaphone,
  bell: Bell,
  phone: Phone,
  radio: Radio,
  send: Send,
  // People
  user: User,
  users: Users,
  contact: Contact,
  hand: Hand,
  // Nature
  leaf: Leaf,
  'flower-2': Flower2,
  'tree-pine': TreePine,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  mountain: Mountain,
  waves: Waves,
  snowflake: Snowflake,
  flame: Flame,
  droplet: Droplet,
  // Science & Tech
  'flask-conical': FlaskConical,
  atom: Atom,
  cpu: Cpu,
  code: Code,
  terminal: Terminal,
  database: Database,
  server: Server,
  bug: Bug,
  'circuit-board': CircuitBoard,
  binary: Binary,
  // Creative
  palette: Palette,
  pen: Pen,
  paintbrush: Paintbrush,
  camera: Camera,
  music: Music,
  film: Film,
  image: Image,
  mic: Mic,
  headphones: Headphones,
  // Status & Emotion
  heart: Heart,
  star: Star,
  flag: Flag,
  trophy: Trophy,
  target: Target,
  bookmark: Bookmark,
  'thumbs-up': ThumbsUp,
  'circle-check': CircleCheck,
  'triangle-alert': TriangleAlert,
  info: Info,
  sparkles: Sparkles,
  crown: Crown,
  // Abstract & Shapes
  circle: Circle,
  square: Square,
  diamond: Diamond,
  hexagon: Hexagon,
  triangle: Triangle,
  zap: Zap,
  hash: Hash,
  'at-sign': AtSign,
  infinity: Infinity,
  // Navigation & Travel
  compass: Compass,
  map: Map,
  globe: Globe,
  house: House,
  rocket: Rocket,
  plane: Plane,
  car: Car,
  ship: Ship,
  signpost: Signpost,
  // Time & Calendar
  clock: Clock,
  calendar: Calendar,
  timer: Timer,
  hourglass: Hourglass,
  // Tools & Objects
  wrench: Wrench,
  hammer: Hammer,
  key: Key,
  lock: Lock,
  shield: Shield,
  link: Link,
  magnet: Magnet,
  scissors: Scissors,
  lightbulb: Lightbulb,
  glasses: Glasses,
  // Data & Charts
  'chart-bar': ChartBar,
  'chart-pie': ChartPie,
  'trending-up': TrendingUp,
  table: Table,
  kanban: Kanban,
  // Education
  'graduation-cap': GraduationCap,
  school: School,
  pencil: Pencil,
  // Food & Drink
  coffee: Coffee,
  pizza: Pizza,
  apple: Apple,
  // Misc
  gift: Gift,
  puzzle: Puzzle,
  'gamepad-2': Gamepad2,
  ticket: Ticket,
  tag: Tag,
  pin: Pin,
  'trash-2': Trash2,
  'wand-sparkles': WandSparkles,
  eye: Eye,
  search: Search,
  settings: Settings,
  // Arrows & Direction
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left-right': ArrowLeftRight,
  'arrow-up-down': ArrowUpDown,
  'arrow-up-right': ArrowUpRight,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'external-link': ExternalLink,
  move: Move,
  'refresh-cw': RefreshCw,
  'rotate-cw': RotateCw,
  // Actions
  plus: Plus,
  minus: Minus,
  x: X,
  'pencil-line': PencilLine,
  save: Save,
  download: Download,
  upload: Upload,
  'share-2': Share2,
  copy: Copy,
  printer: Printer,
  filter: Filter,
  'undo-2': Undo2,
  'redo-2': Redo2,
  'log-in': LogIn,
  'log-out': LogOut,
  // Media
  play: Play,
  pause: Pause,
  'volume-2': Volume2,
  // Layout
  list: List,
  'layout-grid': LayoutGrid,
  'panel-left': PanelLeft,
  menu: Menu,
  'more-horizontal': MoreHorizontal,
  'maximize-2': Maximize2,
  'minimize-2': Minimize2,
  // Status (semantic)
  'x-circle': XCircle,
  'circle-help': CircleHelp,
  loader: Loader,
  // Combat & Gaming
  sword: Sword,
  swords: Swords,
  crosshair: Crosshair,
  skull: Skull,
  // Connectivity
  wifi: Wifi,
  bluetooth: Bluetooth,
  power: Power,
};

export function getPageIcon (lucideName: string): Component | undefined {
  return PAGE_ICONS[lucideName];
}
