---
_label: "rust-analyzer"
_icon: icon.folder
---

[[directory-index]]

This section contains resources and notes about the `rust-analyzer` project.

`rust-analyzer` is an LSP implement for Rust for many code editors.

Official site: [Link](https://rust-analyzer.github.io/).

- [High-Level Architecture & Conventions](01-high-level-architecture-and-conventions)
- [Coding Conventions](02-coding-conventions)
- [Syntax Tree & Parser](03-syntax-tree-and-parser)
- [Writing Tests](04-tests)
